### ISSUE TITLE
bleskomet extension doesn't open

### ISSUE THREAD

**Issue by tlindi** [lnbits/bleskomat#5]
I updated updated from lnbits 0.9.something to 0.11.1 (via MyNode OneClick updates)

Now extension versions 0.1.0 and 0.1.2 both give me: `Error: Object of type URL is not JSON serializable`

Tried to uninstall (keeping database). No avail. I wouldn't like to delete db if possible.

How to debug?

**Comment by dni** [comment]
can you tell me what are you actually doing when the Error pops up, startup?

**Comment by tlindi** [comment]
Click Bleskomat extension on left menu to open it.

________________________________

**Comment by tlindi** [comment]
updated on MyNodeBTC to 0.11.1 

not able to reproduce anymore.
